# Whole Earth Book Catalog : The Data
The data files are organized into separate node files, edge/relationship files, and combined files
## Nodes
There are four different types of nodes: **edition, person, place, and publisher** <br>
- combined_batch.tsv
     - Concatenation of below files with columns: ID, Name, Type, ISBN, and Year
     - The files contain repeated IDs
         - for example: Node with ID, 3 and Name, Paris can be found repeated in the table
     - Column titles not included in file
- place_batch.tsv
    - **Contains IDs: 0 - 9,999,999**
    - **File size:**
    - Below is an example of this table, column titles not included in file <br>

| ID | Name | Type |
| --- | --- | --- |
| 0 | Hamburg | Place |
| 1 | Dresden | Place |
| 2 | Firenze | Place |
| 3 | Paris | Place |
| 4 | Bari | Place |

- edition_batch.tsv
    - **IDs: 10,000,000 - 19,999,999**
    - **File size:**
    - Below is an example of this table, column titles not included in file 

| ID | Name | ISBN  | Year | Type |
| --- | --- | --- | --- | --- |
| 10000000 | Das feldgraue spruchbuch | None | 1941 | Edition |
| 10000001 | Hölle am Panama-kanal, roman | None | 1943 | Edition |
| 10000002 | Fiori freschi | None | 1944 | Edition |
| 10000003 | Guerre et crises économiques face au chômage | None | 1944 | Edition |
| 10000004 | Il dissidio spirituale della Germania con l'Europa. (Ristampa) | None | 1944 | Edition |

- publisher_batch.tsv
    - **IDs: 20,000,000 - 29,999,999**
    - **File size:**
    - Below is an example of this table, column titles not included in file

| ID | Name | Type |
| --- | --- | --- |
| 20000000 | Hanseatische verlagsanstalt | Publisher |
| 20000001 | F. Müller | Publisher |
| 20000002 | Sansoni | Publisher |
| 20000003 | Librairie génerale de droit et de jurisprudence | Publisher |
| 20000004 | G. Laterza | Publisher |
| 20000005 | Zinnen-verlag | Publisher |

- person_batch.tsv
    - **IDs: 30,000,000 - 39,999,999**
    - **File size:**
    - Below is an example of this table, column titles not included in file

| ID | Name | Type |
| --- | --- | --- |
| 30000000 | Gottfried Neesse | Person |
| 30000001 | Wilhelm Alexander von Tayenthal | Person |
| 30000002 | Mario Praz	| Person |
| 30000003 | Jean Lescure | Person |
| 30000004 | Benedetto Croce | Person |

## Edges

There are three different kind of relationships between the nodes: **edition to place, publisher to edition, and person to edition**

- combined_rel_batch.tsv
    - **File size:**
    - Concatenation of below files, columns are ID, ID and titles are not included in the file
- place_rel_batch.tsv
    - **File size:**
    - Below is an example of this table, column titles not included in file

| Edition ID | Place ID |
| --- | --- |
| 10000000 | 0 |
| 10000001 | 1 |
| 10000002 | 2 |
| 10000003 | 3 |
| 10000004 | 4 |

- published_rel_batch.tsv
    - **File size:** 
    - Below is an example of this table, column titles not included in file
    
| Publisher ID | Edition ID |
| --- | --- |
| 20000000 | 10000000 |
| 20000001 | 10000001 |
| 20000002 | 10000002 |
| 20000003 | 10000003 |
| 20000004 | 10000004 |

- wrote_rel_batch.tsv
    - **File size:** 
    - Below is an example of this table, column titles not included in file

| Person ID | Edition ID |
| --- | --- |
| 30000000 | 10000000 |
| 30000001 | 10000001 |
| 30000002 | 10000002 |
| 30000003 | 10000003 |
| 30000004 | 10000004 |